### ISSUE TITLE
Any possability for bridges

### ISSUE THREAD

**Issue by TomLewis** [Dolphindalt/PorteCoulissante#1]
This is amazing you updated this to work for 1.18!
Is there any chance you could also fork the bridges too?
https://sourceforge.net/p/retractablebrdg/code/HEAD/tree/

**Comment by Dolphindalt** [comment]
Thank you for leaving this issue. I will look into updating this bridges plugin and including it with Porte Coulissante once my studies are concluded for the Spring.

**Comment by TomLewis** [comment]
Fantastic! Thank you!

**Comment by Dolphindalt** [comment]
I decided to keep the RetractableBridges as a separate plugin. It was quite painful to update to 1.19, but here it is: [RetractableBridges](https://github.com/Dolphindalt/RetractableBridges)

**Comment by TomLewis** [comment]
This is uttery amazing good news! What made it more difficault to update than the PorteCoulissante plugin?

**Comment by Dolphindalt** [comment]
There was just a lot of legacy bukkit code and hard coded blocks and such. The bridges are more complicated because how power applies to a bridge and taking into account blocked directions is more work. I wanted to rewrite the code completely to make it a little more maintainable. It was a good exercise because I haven't touched Java in a while. I will close this issue now. Please feel free to leave more issues if there are bugs with this plugin or the Bridges. Once again, thank you for requesting the bridges plugin.
